/**
 * Minimal C# type declarations for Puerts benchmark.
 * In production, these are auto-generated by Puerts Gen tool.
 * For now, hand-written for the types we need.
 */

declare module 'csharp' {
  namespace CS {
    namespace UnityEngine {
      class Object {
        name: string;
        GetInstanceID(): number;
        static Destroy(obj: Object): void;
        static FindAnyObjectByType(type: any): any;
      }

      class Component extends Object {
        gameObject: GameObject;
        transform: Transform;
        GetComponent<T>(type: { new(): T }): T | null;
        GetComponent(type: string): Component | null;
      }

      class Behaviour extends Component {
        enabled: boolean;
      }

      class MonoBehaviour extends Behaviour {}

      class Transform extends Component {
        parent: Transform;
        childCount: number;
        localPosition: Vector3;
        localScale: Vector3;
        localEulerAngles: Vector3;
        SetParent(parent: Transform, worldPositionStays?: boolean): void;
        GetChild(index: number): Transform;
        SetSiblingIndex(index: number): void;
      }

      class RectTransform extends Transform {
        anchoredPosition: Vector2;
        sizeDelta: Vector2;
        anchorMin: Vector2;
        anchorMax: Vector2;
        pivot: Vector2;
        rect: Rect;
      }

      class GameObject extends Object {
        transform: Transform;
        activeSelf: boolean;
        activeInHierarchy: boolean;
        constructor(name?: string);
        AddComponent<T>(type: { new(): T }): T;
        AddComponent(type: string): Component;
        GetComponent<T>(type: { new(): T }): T | null;
        GetComponent(type: string): Component | null;
        SetActive(active: boolean): void;
        static Find(name: string): GameObject | null;
      }

      class Canvas extends Behaviour {
        renderMode: number;
        sortingOrder: number;
        worldCamera: Camera;
      }

      class Camera extends Behaviour {
        static main: Camera;
      }

      class CanvasRenderer extends Component {}

      class CanvasGroup extends Behaviour {
        alpha: number;
        blocksRaycasts: boolean;
        interactable: boolean;
      }

      class Vector2 {
        x: number;
        y: number;
        constructor(x: number, y: number);
      }

      class Vector3 {
        x: number;
        y: number;
        z: number;
        constructor(x: number, y: number, z: number);
      }

      class Color {
        r: number;
        g: number;
        b: number;
        a: number;
        constructor(r: number, g: number, b: number, a?: number);
        static red: Color;
        static green: Color;
        static blue: Color;
        static white: Color;
        static black: Color;
      }

      class Rect {
        x: number;
        y: number;
        width: number;
        height: number;
      }

      class Time {
        static realtimeSinceStartup: number;
        static deltaTime: number;
        static frameCount: number;
      }

      class Debug {
        static Log(message: any): void;
        static LogWarning(message: any): void;
        static LogError(message: any): void;
      }

      class Application {
        static dataPath: string;
        static platform: number;
      }

      class Screen {
        static width: number;
        static height: number;
      }

      namespace UI {
        class Graphic extends Behaviour {
          color: Color;
          raycastTarget: boolean;
        }

        class Image extends Graphic {
          sprite: any;
          type: number;
          fillAmount: number;
        }

        class RawImage extends Graphic {
          texture: any;
        }

        class Text extends Graphic {
          text: string;
          fontSize: number;
          alignment: number;
        }

        class Button extends Behaviour {}
        class Toggle extends Behaviour {
          isOn: boolean;
        }
        class Slider extends Behaviour {
          value: number;
          minValue: number;
          maxValue: number;
        }
        class InputField extends Behaviour {
          text: string;
        }
        class ScrollRect extends Behaviour {
          horizontal: boolean;
          vertical: boolean;
        }
        class CanvasScaler extends Behaviour {
          uiScaleMode: number;
          referenceResolution: Vector2;
          matchWidthOrHeight: number;
        }
        class GraphicRaycaster extends Behaviour {}
      }

      namespace EventSystems {
        class EventSystem extends Behaviour {}
        class StandaloneInputModule extends Behaviour {}
      }
    }

    namespace TMPro {
      class TextMeshProUGUI extends UnityEngine.UI.Graphic {
        text: string;
        fontSize: number;
        color: UnityEngine.Color;
      }
    }

    namespace TowerUI {
      class UIBridge {
        static CreateUIGameObject(name: string, parent: UnityEngine.Transform): UnityEngine.GameObject;
        static CreateWithImage(name: string, parent: UnityEngine.Transform): UnityEngine.GameObject;
        static CreateWithText(name: string, parent: UnityEngine.Transform): UnityEngine.GameObject;
        static SetPosition(rt: UnityEngine.RectTransform, x: number, y: number): void;
        static SetSize(rt: UnityEngine.RectTransform, w: number, h: number): void;
        static SetColor(graphic: UnityEngine.UI.Graphic, r: number, g: number, b: number, a: number): void;
        static SetAnchors(rt: UnityEngine.RectTransform, minX: number, minY: number, maxX: number, maxY: number): void;
        static SetPivot(rt: UnityEngine.RectTransform, x: number, y: number): void;
        static SetScale(t: UnityEngine.Transform, x: number, y: number, z: number): void;
        static SetRotation(t: UnityEngine.Transform, x: number, y: number, z: number): void;
        static SetActive(go: UnityEngine.GameObject, active: boolean): void;
        static GetTimeMs(): number;
      }
    }
  }

  export = CS;
}

declare module 'puerts' {
  function $typeof(cls: any): any;
  function $generic(genericType: any, ...typeArgs: any[]): any;
  function $ref(value?: any): { value: any };
  function $unref(ref: { value: any }): any;
  function on(eventName: string, callback: Function): void;
}
