#!/usr/bin/env node

/**
 * @tower-ui/cli — AI-assisted game UI development tool
 *
 * Commands:
 *   tower-ui generate <description> -o <file>   Generate UI from natural language
 *   tower-ui modify <file> <description>         Modify existing UI component
 *   tower-ui from-image <image> -o <file>        Generate UI from screenshot
 *   tower-ui preview                             Start preview server
 *   tower-ui validate <file>                     Validate UI JSON
 *   tower-ui watch                               Watch + HMR dev server
 */

import { TOWER_UI_SCHEMA, validateUI, jsonToTSX, type UINode } from '@tower-ui/schema';
import { startDevServer } from '@tower-ui/preview';
import { handleCreate } from './create';

const args = process.argv.slice(2);
const command = args[0];

function printHelp(): void {
  console.log(`
  tower-ui — AI-assisted Game UI CLI

  Commands:
    create <name> [--dir <path>]   Create a new TowerUI game project
    dev [entry.tsx] [options]      Start web preview dev server (HMR)
    generate <desc> -o <file>      Generate TSX from description
    modify <file> <desc>           Modify existing component
    from-image <img> -o <file>     Generate TSX from screenshot
    validate <json-file>           Validate UI JSON against schema
    schema                         Print component schema
    watch                          Watch files + rebuild

  Options:
    -o, --output <file>    Output file path
    --dir <path>           Target directory for create (default: ./apps)
    --help                 Show help
  `);
}

function handleSchema(): void {
  const schema = TOWER_UI_SCHEMA;
  console.log(`TowerUI Schema v${schema.version}`);
  console.log(`\nComponents (${Object.keys(schema.components).length}):\n`);
  for (const [name, comp] of Object.entries(schema.components)) {
    const props = Object.entries(comp.props)
      .filter(([, d]) => d.required)
      .map(([k]) => k);
    const reqStr = props.length > 0 ? ` [required: ${props.join(', ')}]` : '';
    console.log(`  <${name}> — ${comp.description}${reqStr}`);
  }
}

function handleValidate(file: string): void {
  const fs = require('fs');
  const content = fs.readFileSync(file, 'utf-8');
  let node: UINode;
  try {
    node = JSON.parse(content);
  } catch {
    console.error(`Error: Invalid JSON in ${file}`);
    process.exit(1);
    return;
  }

  const errors = validateUI(node);
  if (errors.length === 0) {
    console.log('Validation passed. No errors found.');
  } else {
    console.error(`Found ${errors.length} error(s):`);
    for (const err of errors) {
      console.error(`  ${err.path}: ${err.message}`);
    }
    process.exit(1);
  }
}

function handleGenerate(description: string, output: string): void {
  // In production this would call an AI API.
  // For now, generate a template based on the description.
  const template: UINode = {
    type: 'ui-view',
    props: {
      width: 600, height: 400,
      flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      gap: 16, padding: 24, tint: '#0d1b2aee',
    },
    children: [
      {
        type: 'ui-text',
        props: { text: description, fontSize: 24, color: '#e0e1dd', width: 552, height: 36, align: 'center', bold: true },
      },
      {
        type: 'ui-text',
        props: { text: 'Generated by tower-ui CLI', fontSize: 14, color: '#778da9', width: 552, height: 20, align: 'center' },
      },
    ],
  };

  const errors = validateUI(template);
  if (errors.length > 0) {
    console.error('Generated template has validation errors:');
    errors.forEach(e => console.error(`  ${e.path}: ${e.message}`));
  }

  const tsx = jsonToTSX(template, pascalCase(output));
  const fs = require('fs');
  fs.writeFileSync(output, tsx, 'utf-8');
  console.log(`Generated: ${output}`);
}

function handleWatch(): void {
  console.log('[tower-ui] Watch mode started');
  console.log('[tower-ui] Watching for TSX file changes...');
  console.log('[tower-ui] In production: chokidar + esbuild incremental + WebSocket to Unity');
  console.log('[tower-ui] Press Ctrl+C to stop');

  // Placeholder: in production this uses chokidar + esbuild + ws
  // chokidar.watch('src/**/*.tsx').on('change', async (path) => {
  //   await esbuild.rebuild();
  //   ws.send('reload');
  // });
}

function pascalCase(s: string): string {
  return s.replace(/\.tsx?$/, '')
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, c => c.toUpperCase());
}

// ── Main ──────────────────────────────────────────────────

switch (command) {
  case 'create': {
    const name = args[1];
    if (!name) { console.error('Usage: tower-ui create <project-name>'); process.exit(1); }
    const dirIdx = args.indexOf('--dir');
    const targetDir = dirIdx >= 0 ? args[dirIdx + 1] : require('path').resolve('apps');
    handleCreate({ name, targetDir });
    break;
  }
  case 'schema':
    handleSchema();
    break;
  case 'validate':
    if (!args[1]) { console.error('Usage: tower-ui validate <file>'); process.exit(1); }
    handleValidate(args[1]);
    break;
  case 'generate': {
    const desc = args[1];
    const oIdx = args.indexOf('-o');
    const output = oIdx >= 0 ? args[oIdx + 1] : 'GeneratedUI.tsx';
    if (!desc) { console.error('Usage: tower-ui generate <description> -o <file>'); process.exit(1); }
    handleGenerate(desc, output);
    break;
  }
  case 'modify':
    console.log('[tower-ui] modify: In production, sends file + description to AI API for targeted edits');
    break;
  case 'from-image':
    console.log('[tower-ui] from-image: In production, sends screenshot to vision AI → schema → TSX');
    break;
  case 'dev':
  case 'preview': {
    const entryArg = args[1];
    const pIdx = args.indexOf('--port');
    const wIdx = args.indexOf('--width');
    const hIdx = args.indexOf('--height');
    const entry = entryArg || require('path').resolve('src/preview.tsx');
    startDevServer({
      entry,
      port: pIdx >= 0 ? Number(args[pIdx + 1]) : 3000,
      width: wIdx >= 0 ? Number(args[wIdx + 1]) : 1280,
      height: hIdx >= 0 ? Number(args[hIdx + 1]) : 720,
    });
    break;
  }
  case 'watch':
    handleWatch();
    break;
  case '--help':
  case 'help':
  case undefined:
    printHelp();
    break;
  default:
    console.error(`Unknown command: ${command}`);
    printHelp();
    process.exit(1);
}
